kiegroup/build-chain-configuration-reader

- .github/workflows/publish.yaml
- .npmrc
> publish flow

- CHANGELOG.md
- docs/tree-example.json
- package.json
- src/lib/helper/definition-interpreter.js
- test/lib/project-tree.test.js
https://issues.redhat.com/browse/BXMSPROD-1025
> archive artifact name default value to project name (without group)

- CHANGELOG.md
- README.md
- docs/tree-example.json
- index.js
- package-lock.json
- package.json
- src/lib/project-tree.js
- src/lib/tree-functionalities.js
- src/lib/util/chain-util.js
- test/index.test.js
- test/lib/project-tree.test.js
- test/lib/tree-functionalities.test.js
- test/lib/util/chain-util.test.js
- test/resources/build-config-with-dependencies-for-example.yaml
- test/resources/project-dependencies.yaml
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1066
> full downstream chain util

- CHANGELOG.md
- README.md
- docs/tree-example.json
- package-lock.json
- package.json
- src/lib/project-tree.js
- src/lib/util/chain-util.js
- src/lib/util/validations.js
- test/lib/project-tree.test.js
- test/lib/tree-functionalities.test.js
- test/lib/util/chain-util.test.js
- test/resources/build-config-dependencies-url-placeholders.yaml
- test/resources/build-config-dependencies-url.yaml
- test/resources/build-config-from-dependencies-extension.yaml
- test/resources/build-config-with-dependencies-for-example.yaml
- test/resources/build-config-with-dependencies.yaml
- test/resources/build-config.yaml
- test/resources/project-dependencies-extension.yaml
- test/resources/project-dependencies-extension2.yaml
- test/resources/project-dependencies.yaml
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1066
We go from
```
- project: kiegroup/optaplanner
dependencies:
- project: kiegroup/drools
mapping:
source: 7.x
target: master
- project: kiegroup/jbpm
mapping:
source: 7.x
target: master
```
To
```
- project: kiegroup/optaplanner
dependencies:
- project: kiegroup/drools
- project: kiegroup/jbpm
mapping:
dependencies:
default:
source: 7.x
target: master
source: master
target: 7.x
exclude:
- kiegroup/optaweb-employee-rostering
- kiegroup/optaweb-vehicle-routing
```
> mapping definition refactored. V2.0

- package-lock.json
- package.json
- project-dependencies.yaml
- src/lib/project-tree.js
- src/lib/util/yaml.js
- test/lib/util/http.test.js
> Reading yaml error treated

- CHANGELOG.md
- README.md
- docs/tree-example.json
- package.json
- src/lib/helper/definition-interpreter.js
- test/lib/helper/definition-interpreter.test.js
related to https://github.com/kiegroup/github-action-build-chain/issues/134
> [ISSUE 134] enable to merge default and specific project commands

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/project-tree.js
- src/lib/reader.js
- src/lib/tree-functionalities.js
- src/lib/util/http.js
- src/lib/util/reader-util.js
- test/lib/project-tree.test.js
- test/lib/reader.test.js
- test/lib/util/http.test.js
https://github.com/kiegroup/github-action-build-chain/issues/142
> [ISSUE 142] read files with token

- docs/tree-example.json
JIRA: [BXMSPROD-1265](https://issues.redhat.com/browse/BXMSPROD-1265)
https://github.com/kiegroup/github-action-build-chain/pull/163
https://github.com/kiegroup/build-chain-configuration-reader/pull/22
When you're fine with this please merge.
@Ginxo There are a bunch of changes still to do for/test!!!! This is not covered with this PRs
> BXMSPROD-1265: Conscientious language initiative

- .github/workflows/publish.yaml
- CHANGELOG.md
- docs/tree-example.json
- package-lock.json
- package.json
- src/lib/reader.js
- test/lib/reader.test.js
> [ISSUE 103] be able to access definition file from private repositories

- README.md
Commit https://github.com/kiegroup/build-chain-configuration-reader/commit/f04674158f82ff798a01a6b16101fdab594a3e51
have changed the branches names and it seems to be wrong.
I can not get the meaning of the section. Can you please correct it?
- link 2
- link 3 etc.
> Read me typo. Mapping section

- CHANGELOG.md
- project-dependencies.yaml
- test/lib/reader.test.js
- test/resources/project-dependencies-exclude.yaml
fix: https://github.com/kiegroup/github-action-build-chain/issues/168
- https://github.com/kiegroup/build-chain-configuration-reader/pull/29
- https://github.com/kiegroup/github-action-build-chain/pull/214
> [ISSUE 168] add exclude mechanism per mapping

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- src/lib/util/mapping-util.js
- test/lib/util/mapping-util.test.js
> getBaseBranch mechanism

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- src/lib/util/mapping-util.js
- test/lib/util/mapping-util.test.js
> Get base mapping info

- src/domain/mapping.ts
- src/util/mapping.ts
- test/util/mapping.test.ts
Resolves #42 sub-task 2
Refactored https://github.com/kiegroup/build-chain-configuration-reader/blob/main/src/lib/util/mapping-util.js
> [ISSUE-42] Sub-task 2: Mapping utils

- src/util/mapping.ts
- src/util/yaml.ts
Fixes all code smells identifies by sonar analysis
> fix code smells identified by sonar

- package-lock.json
- src/tree.ts
- test/resources/tree/tree.yml
- test/tree.test.ts
Resolves #41 
Added `getOrderedListForProject`. It returns upstream + current + downstream nodes where current is the project passed to getOrderedListForProject
TODO `getOrderedListForTree`
> Tree functionalities

- .github/workflows/publish.yml
- .github/workflows/report.yml
- src/reader.ts
fixing https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=kiegroup_build-chain-configuration-reader&open=AYR6G0HvkraiHHP0uvgW
no need to increase library version since the functionality remains the same
> sonar bug fixed

- .github/workflows/publish.yml
- .gitignore
- package-lock.json
- package.json
- src/index.ts
- tsconfig.json
Need to compile before publishing
> prepared for compilation

- package-lock.json
- package.json
- src/util/safe-eval.ts
- test/util/treat-url.test.ts
> Handle eval errors

- package-lock.json
- package.json
- src/util/treat-url.ts
- test/util/treat-url.test.ts
> replace expression before replacing placeholders

- package-lock.json
- package.json
- src/util/treat-url.ts
> fix: use env before default for url placeholder replacements

- README.md
- package-lock.json
- package.json
- src/domain/node.ts
- src/domain/platform.ts
- src/index.ts
- src/schema/platform.ts
- src/util/construct-node.ts
- test/util/yaml.test.ts
> add reserved id for platform with default configurations

- package-lock.json
- package.json
- src/domain/platform.ts
- src/schema/platform.ts
- test/util/yaml.test.ts
Part of https://github.com/kiegroup/github-action-build-chain/issues/442
> add new platform - gerrit

- .github/workflows/publish.yml
- .github/workflows/pull_request.yml
- .github/workflows/report.yml
- package.json
- test/tree.test.ts
fixes https://github.com/kiegroup/build-chain-configuration-reader/issues/109
> upgrades of used GHA
